### PR TITLE
update prometheus-operator to version v0.75.2

### PR DESCRIPTION
**Pull request by ajayk**

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Thanks for the contribution @ajayk , but for this repo we have an automated Dependabot to keep our dependencies up to date, see more at https://github.com/NVIDIA/gpu-operator/blob/main/.github/dependabot.yml#L6

**Comment by ajayk** [comment]
@ArangoGutierrez dependabot had been failing due to api changes on some of the libraries this PR addresses those

**Comment by tariq1890** [comment]
Hi @ArangoGutierrez , @ajayk is correct. We need this changeset to bump the prometheus-operator dependency. While depdendabot can bump the dependencies other than the prometheus-operator, code changes are needed to be able to import the v0.75.2 version

Maybe we could just limit the changeset of this PR to bumping the prometheus-operator dependency

**Comment by ajayk** [comment]
> Hi @ArangoGutierrez , @ajayk is correct. We need this changeset to bump the prometheus-operator dependency. While depdendabot can bump the dependencies other than the prometheus-operator, code changes are needed to be able to import the v0.75.2 version
> 
> Maybe we could just limit the changeset of this PR to bumping the prometheus-operator dependency

I have 

> Hi @ArangoGutierrez , @ajayk is correct. We need this changeset to bump the prometheus-operator dependency. While depdendabot can bump the dependencies other than the prometheus-operator, code changes are needed to be able to import the v0.75.2 version
> 
> Maybe we could just limit the changeset of this PR to bumping the prometheus-operator dependency

Thanks @tariq1890 I made the necessary changes just to include bumping of prometheus-operator dependency

**Comment by tariq1890** [comment]
Thanks @ajayk !

Can you edit the commit message and retitle this PR?

```
update prometheus-operator to version v0.72.5
```

**Comment by ajayk** [comment]
> Thanks @ajayk !
> 
> Can you edit the commit message and retitle this PR?
> 
> ```
> update prometheus-operator to version v0.72.5
> ```

@tariq1890 done !!

**Review by tariq1890 — APPROVED** [review]

**Comment by tariq1890** [comment]
Thanks for your contribution @ajayk !

**Pull request merged**
